sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - npm i npminstall -g
install:
  - npminstall
env:
  - EGG_PASSPORT_QQ_CLIENT_ID=123
  - EGG_PASSPORT_QQ_CLIENT_SECRET=123
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
